### ISSUE TITLE
Javascript is broken on minified

### ISSUE THREAD

**Issue by amrondonp** [JuezUN/INGInious-old#49]
I just created the new server instance online and there are already some bugs

When javascript minified configuration is set to true, the editor, changing language and other new features are broken.

Maybe a solution would be to compile our new javascript, (I think it is using the old JS so it does not work at all)

**Comment by crdgonzalezca** [comment]
Another option to rather than hard coding the hidden containers and subproblems, we might be able to set this as an option in the _configuration.yaml_ file. That way we can choose which are hidden.
